arrowParens: "avoid"
bracketSpacing: true
insertPragma: false
jsxBracketSameLine: false
printWidth: 140
proseWrap: "preserve"
requirePragma: false
semi: true
singleQuote: false
tabWidth: 2
trailingComma: "all"
useTabs: false
